아래 문제들은 결과 출력까시 실행 후 노트북 파일을 제출

1.1차원이면서 크기가 10이고 0으로 채워진 배열을 생성하고 다섯번째 요소를 1로 설정하는 코드를 작성하시오. 

In [13]:
import numpy as np

a = np.zeros((1, 10))
a[0][5] = 1
a


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

2.아래와 같은 배열을 생성하는 code를 작성하시오.
arange 사용

[3,6,9,12,15,18,21]

In [15]:
import numpy as np

np.arange(3, 22, 3)

array([ 3,  6,  9, 12, 15, 18, 21])

3.0부터 8까지의 값을 가지고 크기가 3x3인 행렬을 arange와 reshape 명령어를 이용하여 생성 하시오. 

[[0 1 2]    
 [3,4,5]  
 [6,7,8]]


In [16]:
import numpy as np
a = np.arange(0, 9)
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4.난수로 채워진 3x3 배열을 생성하고 최대값과 최소값을 구하는 코드를 작성 하시오

In [21]:
import numpy as np
a = np.random.rand(3, 3)

print(a.min())
print(a.max())


0.010296210068615586
0.9908609163879847


5.다음과 같은 행렬을 만드는 code를 작성하시오. 
(ones 함수와 slicing 이용)

[[1,1,1,0,0]    
  [1,1,1,0,0]  
  [1,1,1,0,0]   
  [1,1,1,1,1]] 

In [23]:
import numpy as np

a = np.ones((4, 5))
a[0:3, 3:] = 0
a


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1.]])

6.5x5 행렬을 만들어 체스보드 패턴으로 채워보자
( zeros 함수와 slicing 이용)

[[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]]  

In [50]:
import numpy as np

a = np.zeros((5, 5))
a[::2, 1::2] = 1
a[1::2, 0::2] = 1
a

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])